<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ZenMonitor.Core" Version="2.0.0-alpha.5" />
    <PackageVersion Include="ZenMonitor.Core.Hosting" Version="2.0.0-alpha.5" />
  </ItemGroup>

</Project>