[package]
name = "zenmonitor"
version = "0.1.0"
description = "A Tauri App"
authors = ["Akeoott"]
edition = "2024"

[lib]
name = "zenmonitor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.104"
