<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dotnet-backend</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>

    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <OptimizationPreference>Speed</OptimizationPreference>
    <TrimMode>full</TrimMode>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZenMonitor.Core" />
    <PackageReference Include="ZenMonitor.Core.Hosting" />
  </ItemGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <TauriTargetTriple>x86_64-pc-windows-msvc</TauriTargetTriple>
    <ExeExtension>.exe</ExeExtension>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
    <TauriTargetTriple>x86_64-unknown-linux-gnu</TauriTargetTriple>
    <ExeExtension/>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
    <TauriTargetTriple>aarch64-apple-darwin</TauriTargetTriple>
    <ExeExtension/>
  </PropertyGroup>

  <Target Name="CopyToTauri" AfterTargets="Publish">
    <Copy SourceFiles="$(PublishDir)$(AssemblyName)$(ExeExtension)"
          DestinationFiles="..\src-tauri\bin\$(AssemblyName)-$(TauriTargetTriple)$(ExeExtension)" />
  </Target>

</Project>
